from pathlib import Path
import os

ROOT_DIR = Path(__file__).resolve().parent
CACHE_TTL_SECONDS = 3600  # one hour

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
MONGO_DB   = os.getenv("MONGO_DB",   "news_db")

# ✂️  Paste the full RSS list you already have ↓
RSS_FEEDS = [
    'https://www.amarujala.com/rss?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/breaking-news.xml?client=android&client_new=au_revamp',
    'https://hindi.oneindia.com/rss/',
    'https://hindi.news18.com/khabar-rss/',
    'https://www.indiatv.in/rssnews/topstory-uttar-pradesh.xml',
    'https://www.indiatv.in/rssnews/topstory-crime.xml',
    'https://www.bhaskar.com/rss-v1--category-2052.xml',
    'https://www.poojanews.com/uttar-pradesh-news/feed/',
    'https://www.hindustantimes.com/feeds/rss/cities/noida-news/rssfeed.xml',
    'https://www.hindustantimes.com/feeds/rss/cities/lucknow-news/rssfeed.xml',
    'https://timesofindia.indiatimes.com/rssfeeds/8021716.cms',
    'https://timesofindia.indiatimes.com/rssfeeds/3947067.cms',
    'https://timesofindia.indiatimes.com/rssfeeds/3947071.cms',
    'https://www.prabhatkhabar.com/rss-feed',
    'https://www.thehindu.com/rssfeeds/',
    'https://hindi.news18.com/commonfeeds/v1/hin/rss/crime/crime.xml',
    'https://www.livehindustan.com/rss',
    'https://navbharattimes.indiatimes.com/rssfeedsdefault.cms',
    'https://www.amarujala.com/rss/gorakhpur.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/lucknow.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/amroha.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/amethi.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/ambedkar-nagar.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/ayodhya.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/aligarh.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/agra.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/azamgarh.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/etawah.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/unnao.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/ghaziabad.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/noida.xml?client=android&client_new=au_revamp',
    'https://www.amarujala.com/rss/etah.xml',
    'https://www.amarujala.com/rss/auraiya.xml',
    'https://www.amarujala.com/rss/kannauj.xml',
    'https://www.amarujala.com/rss/kanpur.xml',
    'https://www.amarujala.com/rss/kasganj.xml',
    'https://www.amarujala.com/rss/kushinagar.xml',
    'https://www.amarujala.com/rss/kaushambi.xml',
    'https://www.amarujala.com/rss/ghazipur.xml',
    'https://www.amarujala.com/rss/gonda.xml',
    'https://www.amarujala.com/rss/ghatampur.xml',
    'https://www.amarujala.com/rss/chandauli.xml',
    'https://www.amarujala.com/rss/chitrakoot.xml',
    'https://www.amarujala.com/rss/jalaun.xml',
    'https://www.amarujala.com/rss/jaunpur.xml',
    'https://www.amarujala.com/rss/jhansi.xml',
    'https://www.amarujala.com/rss/deoria.xml',
    'https://www.amarujala.com/rss/pilibhit.xml',
    'https://www.amarujala.com/rss/pratapgarh.xml',
    'https://www.amarujala.com/rss/allahabad.xml',
    'https://www.amarujala.com/rss/fatehpur.xml',
    'https://www.amarujala.com/rss/farrukhabad.xml',
    'https://www.amarujala.com/rss/firozabad.xml',
    'https://www.amarujala.com/rss/budaun.xml',
    'https://www.amarujala.com/rss/bareilly.xml',
    'https://www.amarujala.com/rss/balrampur.xml',
    'https://www.amarujala.com/rss/ballia.xml',
    'https://www.amarujala.com/rss/basti.xml',
    'https://www.amarujala.com/rss/bahraich.xml',
    'https://www.amarujala.com/rss/banda.xml',
    'https://www.amarujala.com/rss/baghpat.xml',
    'https://www.amarujala.com/rss/barabanki.xml',
    'https://www.amarujala.com/rss/bijnor.xml',
    'https://www.amarujala.com/rss/bulandshahr.xml',
    'https://www.amarujala.com/rss/bhadohi.xml',
    'https://www.amarujala.com/rss/mau.xml',
    'https://www.amarujala.com/rss/mathura.xml',
    'https://www.amarujala.com/rss/maharajganj.xml',
    'https://www.amarujala.com/rss/mahoba.xml',
    'https://www.amarujala.com/rss/mirzapur.xml',
    'https://www.amarujala.com/rss/muzaffarnagar.xml',
    'https://www.amarujala.com/rss/moradabad.xml',
    'https://www.amarujala.com/rss/meerut.xml',
    'https://www.amarujala.com/rss/mainpuri.xml',
    'https://www.amarujala.com/rss/rampur.xml',
    'https://www.amarujala.com/rss/raebareli.xml',
    'https://www.amarujala.com/rss/lakhimpur-kheri.xml',
    'https://www.amarujala.com/rss/lalitpur.xml',
    'https://www.amarujala.com/rss/varanasi.xml',
    'https://www.amarujala.com/rss/shamli.xml',
    'https://www.amarujala.com/rss/shahjahanpur.xml',
    'https://www.amarujala.com/rss/shravasti.xml',
    'https://www.amarujala.com/rss/sant-kabir-nagar.xml',
    'https://www.amarujala.com/rss/sambhal.xml',
    'https://www.amarujala.com/rss/saharanpur.xml',
    'https://www.amarujala.com/rss/siddharthnagar.xml',
    'https://www.amarujala.com/rss/sitapur.xml',
    'https://www.amarujala.com/rss/sultanpur.xml',
    'https://www.amarujala.com/rss/sonebhadra.xml',
    'https://www.amarujala.com/rss/hamirpur.xml',
    'https://www.amarujala.com/rss/hardoi.xml',
    'https://www.amarujala.com/rss/hathras.xml',
    'https://www.amarujala.com/rss/hapur.xml'
]
